name: preprocessing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
    CSV_URL: "./heart_disease.csv"

jobs:
  preprocess:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Allows the workflow to push changes back to the repo
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.7'

    - name: Install dependencies
      run: pip install numpy pandas matplotlib seaborn missingno scikit-learn 

    - name: Run preprocessing
      run: python preprocessing/automate_Hendy.py

    - name: Commit and push preprocessed files
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
    
        # Stage the untracked file
        git add preprocessing/heart_disease_preprocessed.csv
    
        # Only commit and push if there are actual changes staged
        if ! git diff --cached --quiet; then
          git commit -m "Update preprocessed data"
          git push
        else
          echo "No changes detected. Skipping commit."
        fi
